AirMed/urls.py
from django.urls import include, path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
 path('marcarExame/', include('marcarExame.urls')),
 path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

marcarExame/urls.py
from argparse import Namespace
from django.urls import include, path
from . import views


app_name = 'marcarExame'

urlpatterns = [
    path("", views.login_view, name="login_view"),
    path("dash", views.dash, name="dash"),
    path("register", views.register, name="register"),
    path("logout_user", views.logout_user, name="logout_user"),
    path("about", views.about, name="about"),
    path("registerMedic", views.registerMedic, name="registerMedic"),
    path("createAppointments", views.createAppointments, name="createAppointments"),
    path("pastAppointments", views.pastAppointments, name="pastAppointments"),
    path("scheduleAppointments", views.scheduleAppointments, name="scheduleAppointments"),
    path("futureAppointments", views.futureAppointments, name="futureAppointments"),
    path("myAppointments", views.myAppointments, name="myAppointments"),
    path("myAvailability", views.myAvailability, name="myAvailability"),
    path("<int:appointment_id>/addResult", views.addResult, name="addResult"),
    path("<int:appointment_id>/removeAppointment", views.removeAppointment, name="removeAppointment"),
    path("<int:appointment_id>/joinAppointment", views.joinAppointment, name="joinAppointment"),
    path("reviews", views.reviews, name="reviews")
]

marcarExame/models.py
from xmlrpc.client import MAXINT
from django.contrib.auth.models import User
from django.db import models

class Cliente(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    numUtente = models.CharField(max_length=9)
    dataNascimento = models.DateTimeField()
    telefone = models.CharField(max_length=9)
    morada = models.CharField(max_length=100)

    def __str__(self):
        return self.user.first_name + " " + self.user.last_name


class Medico(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    numMedico = models.CharField(max_length=9)
    dataNascimento = models.DateTimeField()
    telefone = models.CharField(max_length=9)
    morada = models.CharField(max_length=100)
    clinica = models.CharField(max_length=100)
    distrito = models.CharField(max_length=50)

    def __str__(self):
        return "Dr. " + self.user.first_name + " " + self.user.last_name


class Agendamento(models.Model):
    idCliente = models.ForeignKey(Cliente, on_delete=models.CASCADE, blank=True, null=True)
    idMedico = models.ForeignKey(Medico, on_delete=models.CASCADE, blank=True, null=True)
    dataHoraInicio = models.DateTimeField(blank=True, null=True)
    dataHoraFim = models.DateTimeField(blank=True, null=True)
    tipoExame = models.CharField(max_length=50)
    estado = models.BooleanField(default=False)

class Reviews(models.Model):
    idCliente = models.ForeignKey(Cliente, on_delete=models.CASCADE, blank=True, null=True)
    CHOICES = zip( range(1,5), range(1,5) )
    rating = models.IntegerField(choices=CHOICES, blank=True)
    review = models.CharField(max_length=200)

marcarExame/views.py
import os

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User, Group
from django.http import HttpResponseRedirect

from .models import Cliente, Medico, Agendamento, Reviews
from django.shortcuts import get_object_or_404, render
from django.urls import reverse, reverse_lazy
from django.core.files.storage import FileSystemStorage
from django.contrib.auth.decorators import login_required, user_passes_test, permission_required
from django.contrib.auth.models import Permission
from django.contrib import messages
from datetime import datetime
from datetime import timedelta
import smtplib
import random


def loadDefaultContext(request):
    fs = FileSystemStorage()
    isMedic = None
    isClient = None
    if request.user.is_superuser:
        uploaded_file_url = fs.url("profile_picture.png")
    else:
        uploaded_file_url = fs.url(request.user.username + ".png")
        isMedic = request.user.groups.filter(name="Medic").exists()
        isClient = request.user.groups.filter(name="Client").exists()
    context = {'uploaded_file_url': uploaded_file_url,
               'isMedic': isMedic,
               'isClient': isClient}
    return context


def loadDefaultMedicContext(request):
    fs = FileSystemStorage()
    context = {'uploaded_file_url': fs.url(request.user.username + ".png"),
               'isMedic': request.user.groups.filter(name="Medic").exists()}
    return context


def loadDefaultClientContext(request):
    fs = FileSystemStorage()
    context = {'uploaded_file_url': fs.url(request.user.username + ".png"),
               'isClient': request.user.groups.filter(name="Client").exists()}
    return context


def check_normaluser(user):
    return not user.is_superuser


def check_superuser(user):
    return user.is_superuser


def check_medic(user):
    return user.groups.filter(name='Medic').exists()


def check_client(user):
    return user.groups.filter(name='Client').exists()


def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        if not username or not password:
            messages.error(request, 'Fields cannot be left blank')
            return HttpResponseRedirect(reverse('marcarExame:login_view', args=()))
        user = authenticate(username=username, password=password)
        if user is None:
            messages.error(request, 'Invalid Credentials')
            return HttpResponseRedirect(reverse('marcarExame:login_view', args=()))
        login(request, user)
        return HttpResponseRedirect(reverse('marcarExame:dash', args=()))
    return render(request, 'marcarExame/login.html')


@login_required
def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('marcarExame:login_view'))


@login_required
def dash(request):
    return render(request, 'marcarExame/dash.html', loadDefaultContext(request))


def register(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        email = request.POST['email']
        birth_date = request.POST['birth_date']
        phone = request.POST['phone']
        address = request.POST['address']
        nhs = request.POST['nhs']
        if not username or not password or not email or not first_name or not birth_date or not 'img' in request.FILES \
                or not phone or not address or not nhs or not last_name:
            messages.error(request, 'Fields cannot be left blank')
            return HttpResponseRedirect(reverse('marcarExame:register', args=()))
        if len(username) > 50 or len(password) > 50 or len(email) > 50 or len(first_name) > 50 or len(
                last_name) > 50 or len(phone) != 9 or len(nhs) != 9 or len(address) > 100 \
                or not phone.isnumeric() or not nhs.isnumeric():
            messages.error(request, 'Invalid field input(s)')
            return HttpResponseRedirect(reverse('marcarExame:register', args=()))
        birthDate = datetime.strptime(birth_date, '%Y-%m-%d').date()
        if (datetime.now().date() - birthDate) < timedelta(days=365 * 18):
            messages.error(request, 'You must be at least 18 years old to create an account')
            return HttpResponseRedirect(reverse('marcarExame:register', args=()))
        fs = FileSystemStorage()
        uploaded_file = request.FILES['img']
        fileName, extension = os.path.splitext(uploaded_file.name)
        lowerExtension = extension.lower()
        if not (
                lowerExtension == '.jpeg' or lowerExtension == '.png' or lowerExtension == '.gif' or lowerExtension == '.jpg'):
            messages.error(request, 'You must choose an image file')
            return HttpResponseRedirect(reverse('marcarExame:register', args=()))
        try:
            User.objects.get(username=username)
            messages.error(request, 'This username already exists, please choose a different one')
            return HttpResponseRedirect(reverse('marcarExame:register', args=()))
        except:
            user = User.objects.create_user(username, email, password, first_name=first_name, last_name=last_name)
            Cliente(user=user, dataNascimento=birth_date, telefone=phone, morada=address, numUtente=nhs).save()
            p1 = Permission.objects.get(codename="view_agendamento")
            p2 = Permission.objects.get(codename="change_agendamento")
            user.user_permissions.add(p1, p2)

            group = Group.objects.get(name="Client")
            group.user_set.add(user)
            fs.save(username + '.png', request.FILES['img'])
            messages.success(request, 'Client created successfully')
            login(request, authenticate(username=username, password=password))
            return HttpResponseRedirect(reverse('marcarExame:dash', args=()))
    else:
        return render(request, 'marcarExame/register.html')


@login_required
def about(request):
    if request.method == 'POST':
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        email = request.POST['email']
        newPassword = request.POST['password']
        oldPassword = request.POST['current_password']
        if not first_name or not last_name or not email:
            messages.error(request, 'Fields cannot be left blank')
            return HttpResponseRedirect(reverse('marcarExame:about', args=()))
        if len(email) > 50 or len(first_name) > 50 or len(last_name) > 50:
            messages.error(request, 'Invalid field input(s)')
            return HttpResponseRedirect(reverse('marcarExame:about', args=()))
        user = User.objects.get(username=request.user.username)
        user.first_name = first_name
        user.last_name = last_name
        user.email = email
        if newPassword and oldPassword:
            if authenticate(username=request.user.username, password=oldPassword):
                user.set_password(newPassword)
                login(request, user)
            else:
                messages.error(request, 'Invalid Current password')
                return HttpResponseRedirect(reverse('marcarExame:about', args=()))
        user.save()
        if not request.user.is_superuser:
            if 'img' in request.FILES:
                fs = FileSystemStorage()
                uploaded_file = request.FILES['img']
                fileName, extension = os.path.splitext(uploaded_file.name)
                lowerExtension = extension.lower()
                if not (
                        lowerExtension == '.jpeg' or lowerExtension == '.png' or lowerExtension == '.gif' or lowerExtension == '.jpg'):
                    messages.error(request, 'You must choose an image file')
                    return HttpResponseRedirect(reverse('marcarExame:about', args=()))
                fs.delete(request.user.username + ".png")
                fs.save(request.user.username + ".png", request.FILES['img'])
            phone = request.POST['phone']
            address = request.POST['address']
            if not phone or not address:
                messages.error(request, 'Fields cannot be left blank')
                return HttpResponseRedirect(reverse('marcarExame:about', args=()))
            if len(phone) != 9 or len(address) > 100 or not phone.isnumeric():
                messages.error(request, 'Invalid field input(s)')
                return HttpResponseRedirect(reverse('marcarExame:about', args=()))
            if request.user.groups.filter(name="Medic").exists():
                medic = User.objects.get(username=request.user.username).medico
                medic.telefone = phone
                medic.morada = address
                medic.save()
            elif request.user.groups.filter(name="Client").exists():
                client = User.objects.get(username=request.user.username).cliente
                client.telefone = phone
                client.morada = address
                client.save()
        messages.success(request, 'Fields updated successfully')
        return HttpResponseRedirect(reverse('marcarExame:about', args=()))

    fs = FileSystemStorage()
    context = {}
    if request.user.is_superuser:
        context["uploaded_file_url"] = fs.url("profile_picture.png")
    else:
        context["uploaded_file_url"] = fs.url(request.user.username + ".png")
        isMedic = request.user.groups.filter(name="Medic").exists()
        isClient = request.user.groups.filter(name="Client").exists()
        context["isMedic"] = isMedic
        context["isClient"] = isClient
        if isMedic:
            medic = User.objects.get(username=request.user.username).medico
            context["clinic"] = medic.clinica
            context["medicNum"] = medic.numMedico
            context["birth_date"] = medic.dataNascimento

marcarExame/templates/marcarExame/dash.html
<!DOCTYPE html>
<html>
<head>

    {% block title %}
        <title>DashBoard</title>
    {% endblock %}

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'marcarExame/css/dash/style.css' %}">
    <link rel="stylesheet" href="{% static 'marcarExame/css/review.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <script src="{% static 'marcarExame/css/myScripts.js' %}"></script>

    <link rel="icon" type="image/x-icon" href="{% static 'marcarExame/images/favicon.png' %}">

    <style>
        body, h1, h2, h3, h4, h5, h6 {
            font-family: "Raleway", sans-serif
        }
    </style>
</head>


<body class="w3-light-grey w3-content" style="max-width:1600px">

{% block sidebar %}
    <!-- Sidebar/menu -->

    <nav class="w3-sidebar w3-collapse w3-white w3-animate-left" style="z-index:3;width:300px;" id="mySidebar"><br>
        <div class="w3-container">
            <a href="#" onclick="w3_close()" class="w3-hide-large w3-right w3-jumbo w3-padding w3-hover-grey"
               title="close menu">
                <i class="fa fa-remove"></i>
            </a>
            <img src="{{ uploaded_file_url }}?v={{ uploaded_file_url }}" height="150px" width="150px" style="object-fit: cover;" class="w3-round"
                 alt="User Image"><br><br>
            <h4><b>Welcome  {% if request.user.is_superuser %}  {{ request.user.username }} {% else %}
                {{ request.user.first_name }}{% endif %}</b></h4>

        </div>
        <div class="w3-bar-block">
            <a href="{% url 'marcarExame:about' %}" id="about" onclick="highlight(this)"
               class="w3-bar-item w3-button w3-padding"><i class="fa fa-user fa-fw w3-margin-right"></i>About</a>

            {% if request.user.is_superuser %}
                <a href="{% url 'marcarExame:registerMedic' %}" id="register_medic" onclick="highlight(this)"
                   class="w3-bar-item w3-button w3-padding"><i class="fa fa-user fa-fw w3-margin-right"></i>Register
                    Medic</a>
            {% endif %}

            <!-- TODO criar isClient -> solucao temporaria -->
            {% if isMedic %}
            <a href="{% url 'marcarExame:createAppointments' %}" id="schedule_appointments" onclick="highlight(this)"
                class="w3-bar-item w3-button w3-padding"><i class="fa fa-user fa-fw w3-margin-right"></i>
                Create Appointments</a>
            <a href="{% url 'marcarExame:pastAppointments' %}" id="past_appointments" onclick="highlight(this)"
                class="w3-bar-item w3-button w3-padding"><i class="fa fa-user fa-fw w3-margin-right"></i>
                Past Appointments</a>
            <a href="{% url 'marcarExame:futureAppointments' %}" id="future_appointments" onclick="highlight(this)"
                class="w3-bar-item w3-button w3-padding"><i class="fa fa-user fa-fw w3-margin-right"></i>
                Future Appointments</a>
            <a href="{% url 'marcarExame:myAvailability' %}" id="my_availability'" onclick="highlight(this)"
                class="w3-bar-item w3-button w3-padding"><i class="fa fa-user fa-fw w3-margin-right"></i>
                My Availability</a>
            {% endif %}
            {% if isClient %}
            <a href="{% url 'marcarExame:scheduleAppointments' %}" id="create_appointments" onclick="highlight(this)"
                class="w3-bar-item w3-button w3-padding"><i class="fa fa-user fa-fw w3-margin-right"></i>
                Schedule Appointments</a>
            <a href="{% url 'marcarExame:myAppointments' %}" id="my_appointments" onclick="highlight(this)"
                class="w3-bar-item w3-button w3-padding"><i class="fa fa-user fa-fw w3-margin-right"></i>
                My Appointments</a>
            <a href="{% url 'marcarExame:reviews' %}" id="reviews" onclick="highlight(this)"
                class="w3-bar-item w3-button w3-padding"><i class="fa fa-user fa-fw w3-margin-right"></i>
                Review</a>
            {% endif %}



            <a href="{% url 'marcarExame:logout_user' %}" class="w3-bar-item w3-button w3-padding"><i></i>LOGOUT</a>
        </div>
    </nav>

    <!-- Overlay effect when opening sidebar on small screens -->
    <div class="w3-overlay w3-hide-large w3-animate-opacity" onclick="w3_close()" style="cursor:pointer"
         title="close side menu" id="myOverlay"></div>

{% endblock %}

{% block feedback %}

    {% if messages %}
        <div id="ErrorMessages" style="margin-right:800px; margin-left:340px; margin-top:20px">
            <ul>
                {% for message in messages %}
                    <li id="errorAlert" style="text-align:center ;list-style: none ; font-weight: bold"
                            {% if message.tags == "error" %} class="alert alert-danger" {% endif %}
                            {% if message.tags == "success" %} class="alert alert-success" {% endif %}>
                        {{ message }}</li>
                {% endfor %}
            </ul>
        </div>
    {% endif %}

{% endblock %}


<!-- !PAGE CONTENT! -->
<div class="w3-main" style="margin-left:300px">

    <!-- First Photo Grid-->
    <div id="aboutBlock" class="w3-row-padding">

        {% block content %}

        {% endblock %}

    </div>
</div>


<!-- End page content -->

</body>
</html>

marcarExame/templates/marcarExame/futureAppointments.html
{% extends "./dash.html" %}

{% block title %}
    <title>Future Appointments</title>
{% endblock %}

{% block content %}

    <div class="info">
        <h1>Future Appointments</h1>
        <br/>
    </div>

    <div class="container" style="margin-top:20px">
        <form class="form-horizontal" method="post" action="{% url 'marcarExame:futureAppointments' %}"
              enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                <label class="control-label" for="start_date">Start Date:</label>
                <input type="date" class="form-control" id="start_date" name="start_date" required>
            </div>
            <div class="form-group">
                <label class="control-label" for="end_date">End Date:</label>
                <input type="date" class="form-control" id="end_date" name="end_date" required>
            </div>
            <div class="form-group">
                <label class="control-label">Exam Type:</label>
                <select class="form-control" id="exam_type" placeholder="X-Ray, MRI, CAT, ECO" name="exam_type"
                        required>
                    <option value="" disabled selected hidden>Choose an Exam</option>
                    <option value="X-Ray">X-Ray</option>
                    <option value="MRI">MRI</option>
                    <option value="CAT">CAT</option>
                    <option value="ECO">ECO</option>
                </select>
                <br/>
                <button type="submit" class="btn btn-primary">Search</button>
            </div>
        </form>
        {% block filtro %}
        {% endblock %}

        <ul style="margin-top:40px;list-style-type: none;margin-left:-55px;">
            <h2>Results</h2>
            <br/>
            {% for appointment in appointments_list %}
                <li>

                    <button style="pointer-events: none;" appointment_id="{{ appointment.id }}" type="button"
                            class="btn btn-secondary">
                        Exam: {{ appointment.tipoExame }};
                        Date: {{ appointment.dataHoraInicio }}-{{ appointment.dataHoraFim }};
                        Client: {{ appointment.idCliente }}
                    </button>
                    <a href="{% url 'marcarExame:removeAppointment' appointment.id %}" style="margin-left:5px"
                       appointment_id="{{ appointment.id }}" class="btn btn-danger">
                        Cancel <a/>
                </li>
                <br/>
            {% endfor %}
        </ul>

    </div>

{% endblock %}  

marcarExame/templates/marcarExame/myAppointments.html
{% extends "./dash.html" %}

{% load static %}

{% block title %}
    <title>My Appointments</title>
{% endblock %}

{% block content %}

    <div class="info">
        <h1>My Appointments</h1>
        <br/>
    </div>

    <div class="container" style="margin-top:20px">
        <form class="form-horizontal" method="post" action="{% url 'marcarExame:myAppointments' %}"
              enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                <label class="control-label" for="start_date">Start Date:</label>
                <input type="date" class="form-control" id="start_date" name="start_date" required>
            </div>
            <div class="form-group">
                <label class="control-label" for="end_date">End Date:</label>
                <input type="date" class="form-control" id="end_date" name="end_date" required>
            </div>
            <div class="form-group">
                <label class="control-label">Exam Type:</label>
                <select class="form-control" id="exam_type" placeholder="X-Ray, MRI, CAT, ECO" name="exam_type"
                        required>
                    <option value="" disabled selected hidden>Choose an Exam</option>
                    <option value="X-Ray">X-Ray</option>
                    <option value="MRI">MRI</option>
                    <option value="CAT">CAT</option>
                    <option value="ECO">ECO</option>
                </select>
                <br/>
                <button type="submit" class="btn btn-primary">Search</button>
            </div>
        </form>

        <ul style="margin-top:40px;list-style-type: none;margin-left:-55px;">
            <h2>Results</h2>
            <br/>
            {% for appointment in appointments_list %}
                {% if appointment.estado == False %}
                    <li>
                        <button style="pointer-events: none;" appointment_id="{{ appointment.id }}" type="button"
                                class="btn btn-info">
                            Exam: {{ appointment.tipoExame }};
                            Date: {{ appointment.dataHoraInicio }}-{{ appointment.dataHoraFim }};
                            Medic:{{ appointment.idMedico }}
                        </button>
                        <a href="{% url 'marcarExame:removeAppointment' appointment.id %}" style="margin-left:5px"
                           appointment_id="{{ appointment.id }}" class="btn btn-danger">
                            Cancel <a/>
                    </li>
                    <br/>
                {% else %}
                    <li>
                        <a href="static/media/appointment{{ appointment.id }}.zip" download class="btn btn-success">
                            Exam: {{ appointment.tipoExame }};
                            Date: {{ appointment.dataHoraInicio }}-{{ appointment.dataHoraFim }};
                            Medic:{{ appointment.idMedico }}
                            <a/>
                    </li>
                    <br/>
                {% endif %}
            {% endfor %}
        </ul>

    </div>

{% endblock %}  

marcarExame/templates/marcarExame/myAvailability.html
{% extends "./dash.html" %}

{% block title %}
    <title>My Availability</title>
{% endblock %}

{% block content %}

    <div class="info">
        <h1>My Availability</h1>
        <br/>
    </div>

    <div class="container" style="margin-top:20px">
        <form class="form-horizontal" method="post" action="{% url 'marcarExame:myAvailability' %}"
              enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                <label class="control-label" for="start_date">Start Date:</label>
                <input type="date" class="form-control" id="start_date" name="start_date" required>
            </div>
            <div class="form-group">
                <label class="control-label" for="end_date">End Date:</label>
                <input type="date" class="form-control" id="end_date" name="end_date" required>
            </div>
            <div class="form-group">
                <label class="control-label">Exam Type:</label>
                <input class="form-control" id="exam_type" placeholder="X-Ray, MRI, CAT, ECO" name="exam_type" required>
                <br/>
                <button type="submit" class="btn btn-primary">Search</button>
            </div>
        </form>

        <ul style="margin-top:40px;list-style-type: none;margin-left:-55px;">
            <h2>Results</h2>
            <br/>
            {% for appointment in appointments_list %}
                <li>

                    <button style="pointer-events: none;" appointment_id="{{ appointment.id }}" type="button"
                            class="btn btn-secondary">
                        Exam: {{ appointment.tipoExame }};
                        Date: {{ appointment.dataHoraInicio }}-{{ appointment.dataHoraFim }}
                    </button>
                    <a href="{% url 'marcarExame:removeAppointment' appointment.id %}" style="margin-left:5px"
                       appointment_id="{{ appointment.id }}" class="btn btn-danger">
                        Cancel <a/>
                </li>
                <br/>
            {% endfor %}
        </ul>

    </div>

{% endblock %}  

marcarExame/templates/marcarExame/pastAppointments.html
{% extends "./dash.html" %}

{% block title %}
    <title>Past Appointments</title>
{% endblock %}

{% block content %}

    <div class="info">
        <h1>Past Appointments</h1>
        <br/>
    </div>

    <div class="container" style="margin-top:20px">
        <form class="form-horizontal" method="post" action="{% url 'marcarExame:pastAppointments' %}"
              enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                <label class="control-label" for="start_date">Start Date:</label>
                <input type="date" class="form-control" id="start_date" name="start_date" required>
            </div>
            <div class="form-group">
                <label class="control-label" for="end_date">End Date:</label>
                <input type="date" class="form-control" id="end_date" name="end_date" required>
            </div>
            <div class="form-group">
                <label class="control-label">Exam Type:</label>
                <select class="form-control" id="exam_type" placeholder="X-Ray, MRI, CAT, ECO" name="exam_type"
                        required>
                    <option value="" disabled selected hidden>Choose an Exam</option>
                    <option value="X-Ray">X-Ray</option>
                    <option value="MRI">MRI</option>
                    <option value="CAT">CAT</option>
                    <option value="ECO">ECO</option>
                </select>
                <br/>
                <button type="submit" class="btn btn-primary">Search</button>
            </div>
        </form>
        {% block filtro %}
        {% endblock %}

        <ul style="margin-top:40px;list-style-type: none;margin-left:-55px;">
            <h2>Results</h2>
            <br/>
            {% for appointment in appointments_list %}
                <li>
                    {% if appointment.estado == False %}
                        <button style="pointer-events: none;" appointment_id="{{ appointment.id }}" type="button"
                                class="btn btn-warning">
                            Exam: {{ appointment.tipoExame }};
                            Date: {{ appointment.dataHoraInicio }}-{{ appointment.dataHoraFim }};
                            Client:{{ appointment.idCliente }}
                        </button>
                        <form style="margin-top:10px" action="{% url 'marcarExame:addResult' appointment.id %}"
                              method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <label class="btn btn-primary" for="my-file-selector">
                                <input name="result" id="my-file-selector" type="file" style="display:none"
                                       onchange="this.form.submit()">
                                Submit Results
                            </label>
                            <span class='label label-info' id="upload-file-info"></span>
                        </form>
                    {% else %}
                        <button style="pointer-events: none;" appointment_id="{{ appointment.id }}" type="button"
                                class="btn btn-success">
                            Exam: {{ appointment.tipoExame }};
                            Date: {{ appointment.dataHoraInicio }}-{{ appointment.dataHoraFim }};
                            Client:{{ appointment.idCliente }}
                        </button>
                    {% endif %}
                </li>
                <br/>
            {% endfor %}
        </ul>

    </div>

{% endblock %}  